#!/bin/bash

PUBLISHINGNAME=seb-miniblog:latest

docker run --rm \
  --name blog \
  -p 3000:3000 \
  -e PORT=$MINIBLOG_PORT \
  -e MINIBLOG_PASSWORD=$MINIBLOG_PASSWORD \
  -e MINIBLOG_USERNAME=$MINIBLOG_USERNAME \
  $PUBLISHINGNAME